# SPDX-License-Identifier: PMPL-1.0-or-later

defmodule SquisherCorpus.Pipeline.SyncWorker do
  @moduledoc """
  Stage 5: Export patterns and statistics for external consumption.

  Generates:
  - exports/corpus_statistics.json — aggregate stats
  - exports/pattern_catalog.json — discovered patterns with confidence
  - exports/type_frequency.json — empirical type frequency data
  - exports/hypatia_facts.lgt — Logtalk facts for Hypatia learning engine
  """

  use Oban.Worker, queue: :sync, max_attempts: 1

  alias SquisherCorpus.Repo
  alias SquisherCorpus.Schemas.{AnalysisResult, Pattern, ComparisonPair}
  alias SquisherCorpus.Mining.Statistics

  import Ecto.Query

  require Logger

  @exports_dir "exports"

  @impl Oban.Worker
  def perform(%Oban.Job{}) do
    Logger.info("SyncWorker starting export run")

    File.mkdir_p!(@exports_dir)

    export_corpus_statistics()
    export_pattern_catalog()
    export_type_frequency()
    export_hypatia_facts()

    Logger.info("SyncWorker export complete")
    :ok
  end

  defp export_corpus_statistics do
    stats = Statistics.corpus_summary()
    json = Jason.encode!(stats, pretty: true)
    File.write!(Path.join(@exports_dir, "corpus_statistics.json"), json)
    Logger.info("SyncWorker wrote corpus_statistics.json")
  end

  defp export_pattern_catalog do
    patterns =
      Pattern
      |> order_by(desc: :frequency)
      |> Repo.all()
      |> Enum.map(fn p ->
        %{
          type: p.pattern_type,
          frequency: p.frequency,
          description: p.description,
          confidence: p.confidence,
          representative_count: length(p.representative_schemas || [])
        }
      end)

    json = Jason.encode!(%{patterns: patterns, exported_at: DateTime.utc_now()}, pretty: true)
    File.write!(Path.join(@exports_dir, "pattern_catalog.json"), json)
    Logger.info("SyncWorker wrote pattern_catalog.json with #{length(patterns)} patterns")
  end

  defp export_type_frequency do
    freq = Statistics.type_frequency()
    json = Jason.encode!(freq, pretty: true)
    File.write!(Path.join(@exports_dir, "type_frequency.json"), json)
    Logger.info("SyncWorker wrote type_frequency.json")
  end

  defp export_hypatia_facts do
    patterns = Repo.all(Pattern)
    results = Repo.all(from a in AnalysisResult, preload: :schema_file)
    comparisons = Repo.all(ComparisonPair)

    facts = build_logtalk_facts(patterns, results, comparisons)
    File.write!(Path.join(@exports_dir, "hypatia_facts.lgt"), facts)
    Logger.info("SyncWorker wrote hypatia_facts.lgt")
  end

  defp build_logtalk_facts(patterns, results, comparisons) do
    header = """
    %% SPDX-License-Identifier: PMPL-1.0-or-later
    %% Auto-generated by squisher-corpus SyncWorker
    %% Generated: #{DateTime.utc_now()}

    :- object(squisher_corpus_facts).

        :- public(corpus_pattern/4).
        :- public(corpus_analysis/5).
        :- public(corpus_comparison/4).
        :- public(corpus_stat/2).

    """

    pattern_facts =
      patterns
      |> Enum.map(fn p ->
        "    corpus_pattern(#{inspect(p.pattern_type)}, #{p.frequency}, #{Float.round(p.confidence || 0.0, 3)}, #{inspect(p.description || "")})."
      end)
      |> Enum.join("\n")

    analysis_facts =
      results
      |> Enum.take(500)
      |> Enum.map(fn r ->
        format = if r.schema_file, do: r.schema_file.format, else: "unknown"
        classes = Enum.join(r.transport_classes || [], ",")

        "    corpus_analysis(#{r.schema_file_id}, #{inspect(format)}, #{Float.round(r.squishability_score || 0.0, 3)}, #{r.field_count || 0}, #{inspect(classes)})."
      end)
      |> Enum.join("\n")

    comparison_facts =
      comparisons
      |> Enum.take(500)
      |> Enum.map(fn c ->
        "    corpus_comparison(#{c.source_id}, #{c.target_id}, #{inspect(c.forward_class)}, #{Float.round(c.asymmetry_score || 0.0, 3)})."
      end)
      |> Enum.join("\n")

    total_schemas = length(results)
    total_patterns = length(patterns)
    total_comparisons = length(comparisons)

    stat_facts = """
        corpus_stat(total_schemas, #{total_schemas}).
        corpus_stat(total_patterns, #{total_patterns}).
        corpus_stat(total_comparisons, #{total_comparisons}).
    """

    footer = "\n:- end_object.\n"

    header <> pattern_facts <> "\n\n" <> analysis_facts <> "\n\n" <> comparison_facts <> "\n\n" <> stat_facts <> footer
  end

  @doc """
  Schedule a sync/export run.
  """
  def schedule do
    %{}
    |> __MODULE__.new()
    |> Oban.insert()
  end
end
